name: Osiris CSGO Build
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'csgo-end-of-life'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Win32 Release
        # Мы используем флаг /p:PreferredToolArchitecture=x64 для ускорения
        # и /m для параллельной сборки, что часто помогает избежать зависаний
        run: msbuild Osiris.sln /p:Configuration=Release /p:Platform=Win32 /p:PreferredToolArchitecture=x64 /m

      - name: Upload Osiris DLL
        uses: actions/upload-artifact@v4
        with:
          name: Osiris-CSGO-Working
          path: Release/Osiris.dll
