name: Ultimate Build
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'csgo-end-of-life'
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Generate Shaders
        shell: cmd
        run: |
          mkdir Source\Resources\Shaders\Build
          "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\fxc.exe" /T vs_3_0 /Vn default_vs /Fh Source\Resources\Shaders\Build\default_vs.h Source\Resources\Shaders\default_vs.hlsl
          "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\fxc.exe" /T ps_3_0 /Vn default_ps /Fh Source\Resources\Shaders\Build\default_ps.h Source\Resources\Shaders\default_ps.hlsl

      - name: Build Osiris
        run: msbuild Osiris.sln /p:Configuration=Release /p:Platform=Win32

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: Osiris-Ready-To-Inject
          path: Release/Osiris.dll
