name: Simple Build
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'csgo-end-of-life'
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build Win32 Release
        run: msbuild Osiris.sln /p:Configuration=Release /p:Platform=Win32
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Osiris-Working-DLL
          path: Release/Osiris.dll
